## Sets and dictionaries

### Coding lecture

#### Dictionaries

In a competition between lists and dictionaries for the most useful data structure in Python, deciding the winner would be a tough call. Dictionaries are unordered collection of elements indexed through keys. Here an example to elucidate this concept:

In [1]:
# Time for our first dictionary!
d1 = {'k1':433, 'second_key':32.32, '3':True}
d1

{'k1': 433, 'second_key': 32.32, '3': True}

Intuitively, we have stored three values in the dictionary `d1`, namely the integer `433`, the floating value `32.32`, and the value `True`. Each of this value is indexed by a single key: `'k1'` for `433`, `'second_key'` for `32.32`, and `'3'` for `True`.

How can we retrieve a specific value stored in a dictionary? Through its key, of course!

In [2]:
# Retrieving the value corresponding to 'k1'
print(d1['k1'])

433


However, here's the catch: dictionaries are unordered, meaning that elements cannot be retrieved through their supposed position.

In [11]:
# What will this expression return?
print(d1[0])

KeyError: 0

What went wrong? Python is informing us that `0` is not a valid key, and thus no value can be retrieved.

This naturally leads us to an important question: *how do I know which values are valid keys for a specific dictionary?*

The answer is quite simple:

In [4]:
# Peacking inside the hood looking for keys...
list(d1.keys())

['k1', 'second_key', '3']

The `.keys()` method returns an objects that points to the keys inside the dictionary. This is a very lightweight way to give access to this information, but it is not ideal for immediate visualization, thus we used the function `list()` for forcing Python to copy all the key values and returning them as a list (not reccommended for dictionaries with very large number of keys!).

Similarly, we can access all the values in `d1` with the `.values()` method:

In [5]:
# ... and now looking for the values!
list(d1.values())

[433, 32.32, True]

Some additional remarks on dictionaries:

In [6]:
# Dictionaries can be modified
print(d1['k1'])
d1['k1'] = 90
print(d1['k1'])

433
90


In [7]:
# And new elements can be easily be added
d1['fourthElement'] = 'one more value!'
d1['fourthElement']
d1

{'k1': 90, 'second_key': 32.32, '3': True, 'fourthElement': 'one more value!'}

In [8]:
# However, no two identical key values are allowed
d2 = {'key1':120, 'key1':121}
d2

{'key1': 121}

In [9]:
# Two different keys can produce an equal value
d1['fifthElement'] = 'one more value'
d1

{'k1': 90,
 'second_key': 32.32,
 '3': True,
 'fourthElement': 'one more value!',
 'fifthElement': 'one more value'}

#### Sets

Our last data struture is also the most specialized one. Sets in Python correspond quite faithfully to mathematical sets, in which they are unordered collections of unique items. 

In [12]:
# Time for our first set..
s1 = {'a', 'b', 'b', 'c'}
s1

{'a', 'b', 'c'}

Noticed anything? Here a couple of important points:
- We tried to sneak two `'b'` values inside the set, but only unique values are allowed, so we ended up with only one `'b'` value
- Declaring a set is quite similar to declare a dictionary containing only keys. Similar syntax, and items inside the set must be unique as the keys of a dictionaire

What are the uses of sets? First, modelling: you may want to keep track of real-world things that by their nature are unique, like social security numbers of gene ids. Alternatively, you may need to perform mathematical operations like intersection, union, set difference, and in this case sets are the right tools for you.

In [13]:
# let's create a second set, partially overlapping with the first one
s2 = {'b', 'c', 'd'}

# what the union of the two sets will bring us?
s1 | s2

{'a', 'b', 'c', 'd'}

In [14]:
# what about their intersection?
s1 & s2

{'b', 'c'}

In [15]:
# difference?
s1 - s2

{'a'}

In [16]:
# interestingly, the difference operator is not symmetric!
s2 - s1

{'d'}

In [17]:
# unless you use the "symmetric difference" operator, of course!
print(s1 ^ s2)
print(s2 ^ s1)

{'d', 'a'}
{'d', 'a'}


We will deepen our knowledge on dictionaries and sets in our exercise section. For the moment, you may want to visit [Python's official documentation](https://docs.python.org/3/library/stdtypes.html) for more information on the subject.